[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "salem1916", email = "salemnajar9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
jarvis = "jarvis:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
