from enum import StrEnum


class Capability(StrEnum):
    READ_FILE = "READ_FILE"
    WRITE_FILE = "WRITE_FILE"
    DELETE_FILE = "DELETE_FILE"
    OPEN_APPLICATION = "OPEN_APPLICATION"
    CONTROL_APPLICATION = "CONTROL_APPLICATION"
    RUN_COMMAND = "RUN_COMMAND"
    USE_BROWSER = "USE_BROWSER"
    INSTALL_SOFTWARE = "INSTALL_SOFTWARE"
    SEND_EMAIL = "SEND_EMAIL"
    DEPLOY_APPLICATION = "DEPLOY_APPLICATION"
    READ_SYSTEM_INFO = "READ_SYSTEM_INFO"